language: swift

osx_image: xcode10.2

before_install:
  - gem install bundler
  - pod repo update
  - pod install

script:
  - xcodebuild clean build -scheme 'VPN Plus' -workspace 'VPN Plus.xcworkspace' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=12.2'
